title: OS2valghalla
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

defaults:
  - scope:
      path: ""         # alle filer i hele repoet
      type: "pages"    # markdown-sider
    values:
      layout: "default"
      has_toc: false # kommentar: fjerne 'Table of contents'
